/*
 * $Id$
 *
 * Read the costs generated by qtree (or similar programs).
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

int main(int argc, char **argv)
{
  FILE *f;
  int i;

  if (argc < 2)
  {
    fprintf(stderr, "Usage: readcost <file> [ <n> ... ]\n");
    exit(1);
  }

  f = fopen(argv[1], "rb");
  if (f == NULL)
  {
    fprintf(stderr, "readcost: cannot open file!\n");
    exit(2);
  }

  for (i = 2; i < argc; i++)
  {
    long n;
    int c;
    n = strtol(argv[i], (char **) NULL, 0);
    if (errno == ERANGE)
    {
      fprintf(stderr, "readcost: too large\n");
      exit(3);
    }
    if (fseek(f, n, SEEK_SET))
    {
      fprintf(stderr, "readcost: fseek failed!\n");
      exit(4);
    }
    c = getc(f);
    if (c == EOF)
    {
      fprintf(stderr, "readcost: too large\n");
      exit(5);
    }
    printf("Cost(%ld) = %d\n", n, c);
  }

  return 0;
}
